# Generated by Django 4.0.5 on 2022-06-26 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0002_alter_learning_options_learning_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 20, 47, 58, 571729)),
        ),
        migrations.AlterField(
            model_name='learning',
            name='date_watched',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 26, 20, 47, 58, 571787)),
        ),
    ]
