# Generated by Django 4.0.5 on 2022-07-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0003_alter_learning_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learning',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='learning',
            name='date_watched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
